on:
  #push:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        # This probably uses https://github.com/gmzwinge/hello-world-composite-action/action.yml
        #uses: gmzwinge/hello-world-composite-action@main
        # This probably uses https://github.com/gmzwinge/hello-world-composite-action/.github/actions/action/action.yml
        uses: gmzwinge/hello-world-composite-action/.github/actions/action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
